software-development-lab/umltools/web/config/routes.rb
Umlint::Application.routes.draw do
  match '/umlint/index', to: 'umlint#index', via: [:get, :post]
  get 'umlint/tutorial', to: 'umlint#tutorial'
  get '/umlint/about', to: 'umlint#about'
  get '/umlint/checks', to: 'umlint#checks'

  match '/umlint/view', to: 'umlint#view', via: [:get, :post]
  get '/umlint/view_checklist', to: 'umlint#view_checklist'

  get '/umlint/login', to: 'umlint#login'
  match '/umlint/do_login', to: 'umlint#do_login', via: [:get, :post]
  get '/umlint/logout', to: 'umlint#logout'

  get '/umlint/manage_password', to: 'umlint#manage_password'
  post '/umlint/manage_password', to: 'umlint#new_password'

  match '/umlint/edit', to: 'umlint#edit', via: [:get, :post]
  get '/umlint/show_checklist_info', to: 'umlint#show_checklist_info'
  post '/umlint/do_update_checklist', to: 'umlint#do_update_checklist'

  post '/umlint/results', to: 'umlint#results'
  get '/umlint/show_warning_details/:item', to: 'umlint#show_warning_details'
  get '/umlint/:subset', to: 'umlint#index'
  get '/umlint', to: 'umlint#index'

  match '/umlgrader/create_instructor', to: 'umlgrader#create_instructor', via: [:get, :post]
  match '/umlgrader/modify_instructor', to: 'umlgrader#modify_instructor', via: [:get, :post]
  match '/umlgrader/index',   to: 'umlgrader#index',   via: [:get, :post]
  match '/umlgrader/results', to: 'umlgrader#results', via: [:get, :post]
  get 'umlgrader/tutorial', to: 'umlgrader#tutorial'
  get '/umlgrader/checks', to: 'umlgrader#checks'
  match '/umlgrader/view', to: 'umlgrader#view', via: [:get, :post]
  match '/umlgrader/edit', to: 'umlgrader#edit', via: [:get, :post]
  get '/umlgrader/show_checklist_info', to: 'umlgrader#show_checklist_info'
  post '/umlgrader/do_update_checklist', to: 'umlgrader#do_update_checklist'
  get '/umlgrader/about', to: 'umlgrader#about'
  get '/umlgrader/show_grader_results/:item', to: 'umlgrader#show_grader_results'
  get '/umlgrader/create_assignment', to: 'umlgrader#create_assignment'
  get '/umlgrader/modify_assignment/:id', to: 'umlgrader#modify_assignment', as: 'problem'
  get '/umlgrader/view_submissions/:id', to: 'umlgrader#view_submissions', as: 'submissions' # New route for submissions
  get '/umlgrader/download_submission_file/:id', to: 'umlgrader#download_submission_file', as: 'download_submission'
  get '/umlgrader/download_group_submissions/:id/:group_id', to: 'umlgrader#download_group_submissions', as: 'download_group_submissions'
  delete '/umlgrader/delete_assignment/:id', to: 'umlgrader#destroy', as: 'umlgrader_delete'
  post '/umlgrader/upload_assignment', to: 'umlgrader#upload_assignment'
  post '/umlgrader/upload_assignment/:id', to: 'umlgrader#reupload_assignment'
  get 'umlgrader/manage_assignments', to: 'umlgrader#manage_assignments'
  get '/umlgrader/logout', to: 'umlgrader#logout'
  get '/umlgrader/', to: 'umlgrader#index'
  get '/umlgrader/tutorial/download', to: 'umlgrader#download_file'
  match '/umlgrader/download_checklist_file/:checklist_id', to: 'umlgrader#download_checklist_file', as: 'download_checklist_file', via: :get
  match '/umlgrader/upload_checklist_file', to: 'umlgrader#upload_checklist_file', as: 'upload_checklist_file', via: :post
  get '/umlgrader/manage_groups', to: 'umlgrader#manage_groups'
  get '/umlgrader/manage_group/:id', to: 'umlgrader#manage_group', as: 'manage_group'
  post '/umlgrader/group_update_descriptions/:id', to: 'umlgrader#group_update_descriptions', as: 'group_upate_descriptions'
  post '/umlgrader/create_group/', to: 'umlgrader#create_group', as: 'create_group'
  post '/umlgrader/group_add_students/:id', to: 'umlgrader#group_add_students', as: 'group_add_students'
  post '/umlgrader/group_add_problem/:id', to: 'umlgrader#group_add_problem', as: 'group_add_problem'
  delete '/umlgrader/delete_group_student/:group/:student', to: 'umlgrader#delete_group_student', as: 'delete_group_student'
  delete '/umlgrader/delete_group_problem/:group/:problem', to: 'umlgrader#delete_group_problem', as: 'delete_group_problem'
  delete '/umlgrader/delete_group/:id', to: 'umlgrader#delete_group', as: 'delete_group'

  post '/desktop/umlgrader', to: 'umlgrader#desktop_results'
  post '/desktop/umlint', to: 'umlint#desktop_results'
  get '/desktop/', to: 'umlgrader#desktop_options'

end

software-development-lab/umltools/web/app/controllers/umlgrader_controller.rb
require 'zip'
require 'csv'

class UmlgraderController < ApplicationController

  protect_from_forgery :except => [:desktop_results]

  def set_base_url
    @base_url = '/umlgrader'
  end

  # will prompt user for problem and file
  # prompts for problem unless it is set
  def index
    problems = Problem.all_open.to_a
    problems.sort! { |a, b| a.name <=> b.name }
    @problem_options = problems.map { |p| [p.display_name, p.id] }
  end

  def desktop_options
    problems = Problem.all_open.to_a
    problems.sort! { |a, b| a.name <=> b.name }
    problem_options = problems.map { |p| [p.display_name, p.id] }
    checklists = CheckList.check_types
    render :json => {:problems => problem_options, :checklists => checklists}
  end

  def desktop_results
    results
    render :layout => 'api'
  end

  def results
    get_problem
    # && params[:model_file].first: Makes EAP File submission blocked test fail
    @mdl_file = params[:model_file] && params[:model_file].first
    if @problem.nil?
      flash[:error] = "Please select a problem to grade"
      redirect_to "/umlgrader"
    elsif @problem.closed?
      flash[:error] = "Sorry, that problem closed at #{@problem.closed_at}."
      redirect_to "/umlgrader"
    elsif @mdl_file.nil? || @mdl_file.original_filename == ""
      flash[:error] = "Please select a file to grade"
      redirect_to "/umlgrader/#{@problem.id}"
    elsif !@mdl_file.original_filename.match '\.(xmi|mdl|XMI|MDL)$'
      flash[:error] = "must have file extension .mdl or .xmi (Attempted to save as #{@mdl_file.original_filename})"
      redirect_to "/umlgrader"
    else
      # Deletes all previous submissions by this account.
      @problem.submissions.each{|submission|
        if(submission.student_id == session[:account_id])
          submission.destroy
        end
      }

      ip = request.remote_ip
      @sub = Submission.create(@mdl_file, @problem, session[:account_id], ip)
      if @sub.run_checks(params[:generate_diagram]).nil?
        @results = nil
      else
        @sub.reload
        @results = @sub.ordered_suggestions
        @account = Account.find_by_id(session[:account_id])
        if @account.student?
          @account.child.submissions << @sub
          @account.save
        end
      end
    end
  end

  def create_instructor
    if !check_for_instructor
      return
    end
    if request.post?
      if params[:change_password] != params[:confirm_password]
        flash[:error] = 'Passwords do not match!'
        redirect_to umlgrader_create_instructor_path
        return
      end
      if Account.find_by(email_address: params[:email]) != nil
        flash[:error] = 'Email already in use!'
        redirect_to umlgrader_create_instructor_path
        return
      end
      instructor = Account.new
      instructor.email_address = params[:email]
      instructor.password_digest = params[:change_password]
      instructor.given_name = params[:first_name]
      instructor.surname = params[:last_name]
      instructor.organization = params[:organization]
      instructor.account_type = Account::INSTRUCTOR
      saved = instructor.save

      if saved
        flash[:notice] = "Instructor '#{params[:email]}' has been created!"
        redirect_to umlgrader_index_path
      else
        # should probably say why, but at least capture the error
        flash[:notice] = "Error: instructor '#{params[:email]}' not created!"
        redirect_to umlgrader_create_instructor_path
      end
    end
  end

  def modify_instructor
    if !check_for_instructor
      return
    end

    @account = Account.find_by_id(session[:account_id])
    if request.post?
      if @account.password_digest != params[:current_password]
        flash[:error] = 'Incorrect current password!'
        redirect_to umlgrader_modify_instructor_path
        return
      end
      if params[:commit] == 'Delete' # Delete button pressed
        destroy_instructor
      elsif params[:commit] == 'Save' # Save button pressed

        if params[:change_password] != params[:confirm_password]
          flash[:error] = 'Passwords do not match!'
          redirect_to umlgrader_modify_instructor_path
          return
        end
        if @account.email_address != params[:email] &&
           Account.where(:email_address => params[:email]).exists?
          flash[:error] = 'This email address is already in use!'
          redirect_to umlgrader_modify_instructor_path
          return
        end

        @account.email_address = params[:email]

        if !params[:change_password].empty?
          @account.password_digest = params[:change_password]
        end

        @account.given_name = params[:first_name]
        @account.surname = params[:last_name]
        @account.organization = params[:organization]

        @account.save
        flash[:notice] = "Instructor '#{params[:email]}' has been modified!"
        redirect_to umlgrader_index_path
      end
    end
  end

  def destroy_instructor
    @account = Account.find_by_id(session[:account_id])

    unless @account.nil?
      @account.destroy
    end
    flash[:notice] = 'Your instructor account has been deleted!'
    logout
  end


  def destroy
    if !check_for_instructor
      return
    end

    @account = Account.find_by_id(session[:account_id])
    @problem = @account.child.problems.find(params[:id])

    unless @problem.nil?
      Problem.find_by_id(params[:id]).destroy
    end

    redirect_to umlgrader_manage_assignments_path
  end

  def show_grader_results
    @grader_item_id = params[:item]
    @grader_item = @grader_item_id && Suggestion.find(@grader_item_id)
    respond_to do |format|
      format.js
    end
  end

  def checks
    @explanations = Explanation.umlgrader_explanations.delete_if { |e|
      e.name == 'UNKNOWN' || e.name == 'SYNTAX'
    }
    Explanation.reverse_sort!(@explanations)
    @sexplanations = Explanation.reverse_sort Explanation.umlgrader_sequence_explanations
  end

  def view
    @checklists = CheckList.all
    if params[:checklist_id]
      @checklist_id = params[:checklist_id].to_i # 0 if checklist_id not set
      session[:checklist] = @checklist_id
    else
      @checklist_id = session[:checklist].to_i || 0
    end
    if @checklist_id != 0
      @check_list = CheckList.find_by_id @checklist_id
      if @check_list.nil?
        # return it to 0 so just don't get anything displayed; user can then
        #  try to reselect the bad list and will get the error (this s Checkshouldn't
        #  happen anyways)
        @checklist_id = 0
      else
        @included_checks = @check_list.inclusion_map
        @lint_items = Explanation.selectable_umlint_explanations
        @grader_items = Explanation.selectable_umlgrader_explanations
        Explanation.reverse_sort! @lint_items
        Explanation.reverse_sort! @grader_items
      end
    end
  end

  def edit
    if !check_for_instructor
      return
    end
    @account = Account.find_by_id(session[:account_id])
    if params[:commit] == 'Submit'
      upload_checklist_file
      return
    end
    # rwh, 2-mar-13: added following 4 lines to support changing
    #   the checklist being edited - see the first form_tag in edit.html.erb
    if params[:checklist_id]
      @checklist_id = params[:checklist_id].to_i # 0 if checklist_id not set
      session[:checklist] = @checklist_id
    else
      @checklist_id = session[:checklist].to_i || 0
    end
    @check_list   = CheckList.find_by_id(@checklist_id)
    if @check_list
      @included_checks = @check_list.inclusion_map
    else
      @checklist_id = 0 # signal can't find checklist
      # (This could be an error situation, but handle it for now by
      # simply creating a dummy list and handle it later if the
      # user is able to reselect the bad number.)
    end
    if @checklist_id == 0
      # set up empty checklist
      @check_list = CheckList.new
      @check_list.instructor  = @account.child
      @check_list.description = ''
      @check_list.language    = ''
      @check_list.retired     = false
      # note this is not saved at this point
      @included_checks = @check_list.all_checks_enabled
    end
    # ensure have list of explanations
    @read_only = (@check_list.instructor != @account.child)
    @lint_items = Explanation.selectable_umlint_explanations
    @grader_items = Explanation.selectable_umlgrader_explanations
    Explanation.reverse_sort!(@lint_items)
    Explanation.reverse_sort! @grader_items
  end

  def show_checklist_info
    if !check_for_instructor
      return
    end
    @account = Account.find_by_id(session[:account_id])
    @checklist_id = params[:checklist_id]
    @check_list = CheckList.find_by_id(@checklist_id)
    if @check_list
      @included_checks = @check_list.inclusion_map
    else
      @check_list = CheckList.new
      @check_list.instructor  = @account.child
      @check_list.description = ''
      @check_list.language    = ''
      @check_list.retired     = false
      # note this is not saved at this point
      @included_checks = @check_list.all_checks_enabled
    end
    @lint_items = Explanation.selectable_umlint_explanations
    @grader_items = Explanation.selectable_umlgrader_explanations
    Explanation.reverse_sort! @lint_items
    Explanation.reverse_sort! @grader_items
    @read_only = @check_list.instructor != @account.child
    render :partial => 'edit_checklist'
  end

  def download_checklist_file
    if !check_for_instructor
      return
    end
    checklist_id = params[:checklist_id]
    check_list = CheckList.find_by_id(checklist_id)
    filepath = check_list.written_json_string
    send_file(
      "#{filepath}",
      filename: "#{check_list.description}.json",
      type: "application/json",
      disposition: "attachment"
    )
  end

  def upload_checklist_file
    if !check_for_instructor
      return
    end
    @account = Account.find_by_id(session[:account_id])
    @checklist_file = params[:checklist_file] && params[:checklist_file].first

software-development-lab/umltools/web/app/views/umlgrader/_group_delete_problem_confirmation.erb
<div class="modal fade" id="confirmDelete<%= problem.id %>" role="dialog">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal">
                    <span aria-hidden="true">&times;</span><span class="sr-only">Close</span>
                </button>
                <h4 class="modal-title">Confirm Action</h4>
            </div>
            <div class="modal-body">
                <p>Are you sure you want to remove the assignment '<%= problem.name %>'?</p>
            </div>
            <div class="modal-footer">
                <div class="btn-group-centered">
                    <%= link_to 'Yes', delete_group_problem_path(group, problem), :method => 'delete', class: 'btn btn-primary', data: {dismiss: 'modal'} %>
                    <button type="button" class="btn btn-default" data-dismiss="modal">No</button>
                </div>
            </div>
        </div>
    </div>
</div>

software-development-lab/umltools/web/app/views/umlgrader/_group_delete_student_confirmation.erb
<div class="modal fade" id="confirmDelete<%= student.id %>" role="dialog">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal">
                    <span aria-hidden="true">&times;</span><span class="sr-only">Close</span>
                </button>
                <h4 class="modal-title">Confirm Action</h4>
            </div>
            <div class="modal-body">
                <p>Are you sure you want to remove the student '<%= student.email_address %>'?</p>
            </div>
            <div class="modal-footer">
                <div class="btn-group-centered">
                    <%= link_to 'Yes', delete_group_student_path(group, student), :method => 'delete', class: 'btn btn-primary', data: {dismiss: 'modal'} %>
                    <button type="button" class="btn btn-default" data-dismiss="modal">No</button>
                </div>
            </div>
        </div>
    </div>
</div>

software-development-lab/umltools/web/app/views/umlgrader/_modal_delete_confirmation.erb
<div class="modal fade" id="confirmDelete<%= problem.id %>" role="dialog">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal">
                    <span aria-hidden="true">&times;</span><span class="sr-only">Close</span>
                </button>
                <h4 class="modal-title">Confirm Action</h4>
            </div>
            <div class="modal-body">
                <p>Are you sure you want to remove the assignment '<%= problem.name %>'?</p>
            </div>
            <div class="modal-footer">
                <div class="btn-group-centered">
                    <%= link_to 'Yes', umlgrader_delete_path(problem), :method => 'delete', class: 'btn btn-primary', data: {dismiss: 'modal'} %>
                    <button type="button" class="btn btn-default" data-dismiss="modal">No</button>
                </div>
            </div>
        </div>
    </div>
</div>

software-development-lab/umltools/web/app/views/umlgrader/create_instructor.erb
<div class="grader_header_title">
  Create Instructor
</div>

<div class="grader-textarea">
  <p>
    Use the following form to create a new instructor.
  </p>
  <br/>

  <% if flash and flash[:error] %>
      <p class=error><%= flash[:error] %></p>
  <% end %>

  <%= render "umlgrader/instructor_form", :modify => false %>

</div>

software-development-lab/umltools/web/app/views/umlgrader/index.html.erb
<!--<TITLE>UMLGrader: Object-oriented model grader</TITLE>-->
<script >
    $(function () {
        $(":file").filestyle();
    });
</script>


<div class=grader_header_title>
  UMLGrader: Object Oriented Model Grader
</div>

<div class="grader-textarea">

  <% if flash and flash[:notice] %>
      <div class="col-lg-6">
        <div class="alert alert-success fade in centered-text" role="alert">
          <button type="button" class="close" data-dismiss="alert">
            <span aria-hidden="true">×</span><span class="sr-only">Close</span></button>
          <%= flash[:notice] %>
        </div>
      </div>
  <% end %>

  <% if flash and flash[:error] %>
      <div class="col-lg-6">
        <div class="alert alert-danger fade in centered-text" role="alert">
          <button type="button" class="close" data-dismiss="alert">
            <span aria-hidden="true">×</span><span class="sr-only">Close</span></button>
          <%= flash[:error] %>
        </div>
      </div>
  <% end %>

  <div class="col-xs-12">
    <p>
      Browse to your solution file, select an assignment, and click on 'Check Diagram' to
      compare your diagram against a standard solution.
    </p>

    <!-- the multipart is what allows upload files: -->
    <%= form_tag('/umlgrader/results', :multipart => true) do %>

        <table>
          <tr>
            <td class=input_item>Model (.mdl or .xmi) file:</td>
            <td class=input_item>
              <%= file_field :model_file, '', :size => 60, :class => 'filestyle' %>
          </tr>
          <tr>
            <td class=input_item>Assignment:</td>
            <td class=input_item><%=
                select_tag 'assignment',
                           options_for_select(@problem_options, @problem && @problem.id), :class => 'form-control' %>
          </tr>
          <tr>
            <td class="input_item">Generate Diagram(If available)?&nbsp;</td>

            <td class="input_item">
              <%= check_box_tag 'generate_diagram' %>
            </td>
          </tr>
          <tr>
            <td>&nbsp;</td>
            <td class=input_item><%= submit_tag 'Check Diagram', :class => 'btn btn-default' %></td>
          </tr>
          <tr>
            <td>&nbsp;</td>
          </tr>
          <tr>
            <td>&nbsp;</td>
          </tr>
        </table>

    <% end %>

    <!--
    <p>First time using UML Grader? No problem! Click <%= link_to 'here', umlgrader_tutorial_path %> for a tutorial.</p>
    -->
  </div>
</div>

software-development-lab/umltools/web/app/views/umlgrader/manage_assignments.html.erb
<div class=grader_header_title>
    Manage Assignment
</div>

<div class="grader-textarea row">
    <% if flash and flash[:msg] %>
        <div style="text-align: center;">
          <p style="color:green"><b><%= flash[:msg] %></b></p>
        </div>
    <% end %>
    <% if flash and flash[:notice] %>
        <div class="col-lg-6 row">
            <div class="alert alert-success fade in centered-text" role="alert">
                <button type="button" class="close" data-dismiss="alert">
                    <span aria-hidden="true">×</span><span class="sr-only">Close</span>
                </button>
                <%= flash[:notice] %>
            </div>
        </div>
    <% end %>

    <div class="col-xs-12">
        <% if (@account_problems && @account_problems.length > 0) %>
            <p>
                This is a list of all the assignments you have created. From here you can modify the settings for any
                assignments
                or remove those that are are outdated.
            </p>

            <div class="table-responsive">
                <table class="table table-striped table-hover table-bordered">
                    <thead>
                    <tr>
                        <td>
                            Name
                        </td>
                        <td>Diagram Type</td>
                        <td>
                            Description
                        </td>
                        <td style="width:1px">
                            Submissions
                        </td>
                        <td style="width:1px">
                            Edit
                        </td>
                        <td style="width:1px">
                            Remove
                        </td>
                    </tr>
                    </thead>
                    <tbody>
                    <% @account_problems.each do |problem| %>
                        <tr>
                            <td><%= problem.name %></td>
                            <td><%= Problem::DIAGRAM_TYPE_NAME[problem.assignment_type.to_i] %></td>
                            <td>
                                <span class="tooltip-haver" data-toggle="tooltip" data-placement="top" title="<%= problem.description %>">
                                    <%= problem.description.length < 100 ? problem.description :
                                                problem.description.slice(0, 100).concat(' ...') %>
                                </span>
                            </td>
                            <td class="center-text">
                                <%= link_to raw('<i class="fa fa-edit"></i>'), submissions_path(problem.id) %>
                            </td>
                            <td class="center-text">
                                <%= link_to raw('<i class="fa fa-edit"></i>'), problem_path(problem.id) %>
                            </td>
                            <td class="center-text">
                                <i class="fa fa-trash pointer" data-toggle="modal" data-target="#confirmDelete<%= problem.id %>"></i>
                                <%= render 'umlgrader/modal_delete_confirmation', :problem => problem %>
                            </td>
                        </tr>
                    <% end %>
                      <tr>
                        <td colspan=6> <a href="/umlgrader/create_assignment">Click here to add a new assignment.</a> </td>
                      </tr>
                    </tbody>
                </table>
            </div>
        <% else %>
            <p>It appears that you haven't created any assignments yet.
                <a href="/umlgrader/create_assignment">Click here</a> to add one.</p>
        <% end %>
    </div>
</div>

software-development-lab/umltools/web/app/views/umlgrader/manage_group.html.erb
<!--<TITLE>UMLGrader: Object-oriented model grader</TITLE>-->
<script >
    $(function () {
        $(":file").filestyle();
    });
</script>


<div class=grader_header_title>
  UMLGrader: Object Oriented Model Grader
</div>

<div class="grader-textarea">
  <table>
    <% if flash and flash[:success] %>
        <div class="col-lg-6">
          <div class="alert alert-success fade in centered-text" role="alert">
            <button type="button" class="close" data-dismiss="alert">
              <span aria-hidden="true">×</span><span class="sr-only">Close</span></button>
            <%= flash[:success] %>
          </div>
        </div>
    <% end %>
    <% if flash and flash[:notice] %>
      <tr>
        <div class="col-lg-6">
          <div class="alert alert-warning fade in centered-text" role="alert">
            <button type="button" class="close" data-dismiss="alert">
              <span aria-hidden="true">×</span><span class="sr-only">Close</span></button>
            <%= flash[:notice] %>
          </div>
        </div>
      </tr>
    <% end %>
    <% if flash and flash[:error] %>
      <tr>
        <div class="col-lg-6">
          <div class="alert alert-danger fade in centered-text" role="alert">
            <button type="button" class="close" data-dismiss="alert">
              <span aria-hidden="true">×</span><span class="sr-only">Close</span></button>
            <%= flash[:error] %>
          </div>
        </div>
      </tr>
    <% end %>
  </table>
  <%= form_tag(@group.new_record? ? "/umlgrader/create_group/" : "/umlgrader/group_update_descriptions/#{@group.id}", :multipart => true) do %>
  <%= link_to @group.new_record? ? "Cancel": "Done", umlgrader_manage_groups_path, class: 'btn btn-default' %>
      <table>
          <tr>
              <td class="input_item"><%= label_tag :name %></td>
              <td class="input_item"><%= text_field_tag :name, @group.name, :placeholder => 'Group Name', class: 'form-control' %></td>
          </tr>
          <tr>
              <td class="input_item"><%= label_tag :description %></td>
              <td class="input_item" style="padding-bottom: 1em"><%= text_field_tag :description, @group.description, :placeholder => 'Group Description', class: 'form-control' %></td>
          </tr>
          <tr>
            <td></td>
            <td><%= submit_tag @group.new_record? ? 'Create Group' : 'Update Descriptions', data: { disable_with: false }, class: 'btn btn-default' %></td>
          </tr>
      </table>
  <% end %>

<% if(!@group.new_record?) %>
      <div role="tabpanel" style="padding: 20px 10px">
        <ul class="nav nav-tabs" role="tablist">
          <li role="presentation" class="active">
            <a href="#students" class="tab-h" aria-controls="students" role="tab" data-toggle="tab">Students</a>
          </li>
          <li role="presentation">
            <a href="#assignments" class="tab-h" aria-controls="assignments" role="tab" data-toggle="tab">Assignments</a>
          </li>
        </ul>

        <div class="tab-content">
          <div role="tabpanel" class="tab-pane active" id="students">
            <div class="table-responsive" style="padding: 20px 10px">
                <%= render 'umlgrader/group_students', group: @group %>
            </div>
          </div>
          <div role="tabpanel" class="tab-pane" id="assignments">
            <div class="table-responsive" style="padding: 20px 10px">
                <%= render 'umlgrader/group_problems', group: @group %>
            </div>
          </div>
        </div>
      </div>
<% end %>
</div>

software-development-lab/umltools/web/app/views/umlgrader/tutorial.erb
<!DOCTYPE html>
<html>
<head>
</head>
<body>
    <div class=grader_header_title>
      UMLGrader: Object Oriented Model Grader
    </div>

    <div class="grader-textarea">
        <div class="col-xs-12">
          <h1>Tutorial</h1>
          <ol>
            <li><h3>Create a class or sequence diagram in a program capable of exporting to XMI format such as Enterprise Architect.</h3></li>
            <ul>
              <li>You may be tempted to structure your project like the pictures below.</li>
              <li>Do NOT do this!</li>
              <%= image_tag("Tutorial-Screenshot-7.png", :alt => "Do NOT do this!") %>
              <%= image_tag("Tutorial-Screenshot-6.png", :alt => "Do NOT do this!") %>
              <li>Instead use a workflow like the one in the picture below.</li>
              <li>If you don't, the generated XMI will contain elements of both the class and sequence diagram.</li>
              <%= image_tag("Tutorial-Screenshot-9.png", :alt => "Do (do) this!") %>
            </ul>
            <li><h3>Export the created package to generate an XMI file.</h3></li>
            <ul>
              <li>Use the menu to select the package you want to export.</li>
              <%= image_tag("Tutorial-Screenshot-0.png", :alt => "File menu (the right way). :D") %>
            <li>Choose the desired path, and then click the 'export' button.</li>
              <%= image_tag("Tutorial-Screenshot-1.png", :alt => "Export XMI.") %>
            </ul>
            <li><h3>Submit the assignment via UMLGrader.</h3></li>
            <ul>
              <li>Select the assignment specified by your instructor.</li>
              <li>Choose and upload the appropriate assignment.</li>
              <%= image_tag("Tutorial-Screenshot-10.png", :alt => "Submit an assignment.") %>
            </ul>
            <li><h3>View submission results.</h3></li>
            <ul>
              <%= image_tag("Tutorial-Screenshot-11.png", :alt => "View results.") %>
            </ul>
          </ol>
          <h1>Sample Files</h1>
          <ul>
            <h3>The sample file package includes the following files.</h3>
            <ul>
              <li>Class Diagram [EAP]</li>
              <li>Sequence Diagram [EAP]</li>
              <li>Class Diagram (Problem) [XMI]</li>
              <li>Class Diagram (Solution) [XMI]</li>
              <li>Sequence Diagram (Problem) [XMI]</li>
              <li>Sequence Diagram (Solution) [XMI]</li>
            </ul>
            <h3><%= link_to 'Sample File Pack Download', umlgrader_tutorial_download_path %></h3>
          </ul><br>
          <%= link_to 'Back To UMLGrader', umlgrader_path %>
        </div>
    </div>
</body>
</html>