software-development-lab/umltools/web/config/routes.rb
Umlint::Application.routes.draw do
  match '/umlint/index', to: 'umlint#index', via: [:get, :post]
  get 'umlint/tutorial', to: 'umlint#tutorial'
  get '/umlint/about', to: 'umlint#about'
  get '/umlint/checks', to: 'umlint#checks'

  match '/umlint/view', to: 'umlint#view', via: [:get, :post]
  get '/umlint/view_checklist', to: 'umlint#view_checklist'

  get '/umlint/login', to: 'umlint#login'
  match '/umlint/do_login', to: 'umlint#do_login', via: [:get, :post]
  get '/umlint/logout', to: 'umlint#logout'

  get '/umlint/manage_password', to: 'umlint#manage_password'
  post '/umlint/manage_password', to: 'umlint#new_password'

  match '/umlint/edit', to: 'umlint#edit', via: [:get, :post]
  get '/umlint/show_checklist_info', to: 'umlint#show_checklist_info'
  post '/umlint/do_update_checklist', to: 'umlint#do_update_checklist'

  post '/umlint/results', to: 'umlint#results'
  get '/umlint/show_warning_details/:item', to: 'umlint#show_warning_details'
  get '/umlint/:subset', to: 'umlint#index'
  get '/umlint', to: 'umlint#index'

  match '/umlgrader/create_instructor', to: 'umlgrader#create_instructor', via: [:get, :post]
  match '/umlgrader/modify_instructor', to: 'umlgrader#modify_instructor', via: [:get, :post]
  match '/umlgrader/index',   to: 'umlgrader#index',   via: [:get, :post]
  match '/umlgrader/results', to: 'umlgrader#results', via: [:get, :post]
  get 'umlgrader/tutorial', to: 'umlgrader#tutorial'
  get '/umlgrader/checks', to: 'umlgrader#checks'
  match '/umlgrader/view', to: 'umlgrader#view', via: [:get, :post]
  match '/umlgrader/edit', to: 'umlgrader#edit', via: [:get, :post]
  get '/umlgrader/show_checklist_info', to: 'umlgrader#show_checklist_info'
  post '/umlgrader/do_update_checklist', to: 'umlgrader#do_update_checklist'
  get '/umlgrader/about', to: 'umlgrader#about'
  get '/umlgrader/show_grader_results/:item', to: 'umlgrader#show_grader_results'
  get '/umlgrader/create_assignment', to: 'umlgrader#create_assignment'
  get '/umlgrader/modify_assignment/:id', to: 'umlgrader#modify_assignment', as: 'problem'
  get '/umlgrader/view_submissions/:id', to: 'umlgrader#view_submissions', as: 'submissions' # New route for submissions
  get '/umlgrader/download_submission_file/:id', to: 'umlgrader#download_submission_file', as: 'download_submission'
  get '/umlgrader/download_group_submissions/:id/:group_id', to: 'umlgrader#download_group_submissions', as: 'download_group_submissions'
  delete '/umlgrader/delete_assignment/:id', to: 'umlgrader#destroy', as: 'umlgrader_delete'
  post '/umlgrader/upload_assignment', to: 'umlgrader#upload_assignment'
  post '/umlgrader/upload_assignment/:id', to: 'umlgrader#reupload_assignment'
  get 'umlgrader/manage_assignments', to: 'umlgrader#manage_assignments'
  get '/umlgrader/logout', to: 'umlgrader#logout'
  get '/umlgrader/', to: 'umlgrader#index'
  get '/umlgrader/tutorial/download', to: 'umlgrader#download_file'
  match '/umlgrader/download_checklist_file/:checklist_id', to: 'umlgrader#download_checklist_file', as: 'download_checklist_file', via: :get
  match '/umlgrader/upload_checklist_file', to: 'umlgrader#upload_checklist_file', as: 'upload_checklist_file', via: :post
  get '/umlgrader/manage_groups', to: 'umlgrader#manage_groups'
  get '/umlgrader/manage_group/:id', to: 'umlgrader#manage_group', as: 'manage_group'
  post '/umlgrader/group_update_descriptions/:id', to: 'umlgrader#group_update_descriptions', as: 'group_upate_descriptions'
  post '/umlgrader/create_group/', to: 'umlgrader#create_group', as: 'create_group'
  post '/umlgrader/group_add_students/:id', to: 'umlgrader#group_add_students', as: 'group_add_students'
  post '/umlgrader/group_add_problem/:id', to: 'umlgrader#group_add_problem', as: 'group_add_problem'
  delete '/umlgrader/delete_group_student/:group/:student', to: 'umlgrader#delete_group_student', as: 'delete_group_student'
  delete '/umlgrader/delete_group_problem/:group/:problem', to: 'umlgrader#delete_group_problem', as: 'delete_group_problem'
  delete '/umlgrader/delete_group/:id', to: 'umlgrader#delete_group', as: 'delete_group'

  post '/desktop/umlgrader', to: 'umlgrader#desktop_results'
  post '/desktop/umlint', to: 'umlint#desktop_results'
  get '/desktop/', to: 'umlgrader#desktop_options'

end

software-development-lab/umltools/web/app/controllers/umlint_controller.rb
class UmlintController < ApplicationController
  respond_to :html, :js

  protect_from_forgery :except => [:desktop_results]

  def set_base_url
    @base_url = '/umlint'
  end

  def index
    @checklist_id = session[:checklist] || 0
  end

  def desktop_results
    results
    render :layout => 'api'
  end

  def results

    check_list_id = params[:checklist_id]
    if check_list_id
      session[:checklist] = check_list_id
      @check_list = CheckList.find_by_id check_list_id # nil if no such check list
    end

    file_type_id = params[:file_type_id]

    # otherwise, run checks

    @mdl_file = params[:model_file] && params[:model_file].first
    if @mdl_file.nil? || @mdl_file.original_filename == ""
      flash[:error] = "Please select a file to check"
      redirect_to "/umlint/#{@subset}"
    else
      ip = request.remote_ip
      @sub = Submission.create(@mdl_file, @check_list, file_type_id, ip)
      if @sub.run_checks(params[:generate_diagram]).nil?
        @suggestions = nil
      else
        @sub.reload
        @suggestions = @sub.ordered_suggestions
      end
    end
  end

  def checks
    @explanations = Explanation.umlint_explanations.delete_if { |e|
      e.name == 'UNKNOWN' || e.name == 'SYNTAX'
    }
    Explanation.reverse_sort!(@explanations)
  end

  def view
    # rwh, 2-mar-13: added following 4 lines to support changing
    #   the checklist that was viewed - see the first form_tag in view.html.erb
    if params[:checklist_id]
      @checklist_id = params[:checklist_id].to_i # 0 if checklist_id not set
      session[:checklist] = @checklist_id
    else
      @checklist_id = session[:checklist].to_i || 0
    end
    if @checklist_id != 0
      @check_list = CheckList.find_by_id(@checklist_id)
      if @check_list.nil?
        # return it to 0 so just don't get anything displayed; user can then
        #  try to reselect the bad list and will get the error (this shouldn't
        #  happen anyways)
        @checklist_id = 0
      else
        @included_checks = @check_list.inclusion_map
        @items = Explanation.selectable_umlint_explanations
        Explanation.reverse_sort!(@items)
      end
    end
    # note: _view_checklist partial handles case where @checklist_id is 0
  end

  def view_checklist
    @checklist_id = params[:checklist_id].to_i # 0 if checklist_id not set
    @check_list = CheckList.find_by_id(@checklist_id)
    if @checklist_id == 0
      # partial will take care of ensuring nothing is displayed
      flash[:error] = ''
      @check_list = nil
      render :partial => 'view_checklist'
      return
    elsif @check_list.nil?
      flash[:error] = "Internal error: no checklist with id #{@checklist_id}"
      redirect_to "/umlint/view"
      return
    end
    @included_checks = @check_list.inclusion_map
    @items = Explanation.selectable_umlint_explanations
    Explanation.reverse_sort!(@items)
    render :partial => 'view_checklist'
  end

  def edit
    if need_login?              # sets @account
      session[:return_to] = request.fullpath
      redirect_to '/umlint/login'
      return
    end
    # rwh, 2-mar-13: added following 4 lines to support changing
    #   the checklist being edited - see the first form_tag in edit.html.erb
    if params[:checklist_id]
      @checklist_id = params[:checklist_id].to_i # 0 if checklist_id not set
      session[:checklist] = @checklist_id
    else
      @checklist_id = session[:checklist].to_i || 0
    end
    @check_list   = CheckList.find_by_id(@checklist_id)
    if @check_list
      @included_checks = @check_list.inclusion_map
    else
      @checklist_id = 0 # signal can't find checklist
      # (This could be an error situation, but handle it for now by
      # simply creating a dummy list and handle it later if the
      # user is able to reselect the bad number.)
    end
    if @checklist_id == 0
      # set up empty checklist
      @check_list = CheckList.new
      @check_list.instructor  = @account
      @check_list.description = ''
      @check_list.language    = ''
      @check_list.retired     = false
      # note this is not saved at this point
      @included_checks = @check_list.all_checks_enabled
    end
    # ensure have list of explanations
    @items = Explanation.selectable_umlint_explanations
    Explanation.reverse_sort!(@items)
  end

  def show_checklist_info
    if need_login?      # sets @account
      session[:return_to] = request.fullpath
      redirect_to '/umlint/login'
      return
    end
    @checklist_id = params[:checklist_id]
    @check_list = CheckList.find_by_id(@checklist_id)
    if @check_list
      @included_checks = @check_list.inclusion_map
    else
      @check_list = CheckList.new
      @check_list.instructor  = @account
      @check_list.description = ''
      @check_list.language    = ''
      @check_list.retired     = false
      # note this is not saved at this point
      @included_checks = @check_list.all_checks_enabled
    end
    @items = Explanation.selectable_umlint_explanations
    Explanation.reverse_sort!(@items)
    @read_only = @check_list.instructor != @account
    render :partial => 'edit_checklist'
  end

  def show_suggestion_details
    @suggestion_item_id = params[:item]
    @suggestion_item = @suggestion_item_id && Suggestion.find(@suggestion_item_id)
    respond_to do |format|
      format.js
    end
  end

  def do_update_checklist
    if params[:commit] == 'Cancel'
      redirect_to '/umlint'
      return
    end
    if need_login?      # sets @account
      session[:return_to] = request.fullpath
      redirect_to '/umlint/login'
      return
    end
    # sample params: see CheckList.updated_to
    checklist_id = params[:checklist_id]
    if checklist_id.nil? || checklist_id == '0'
      checklist = CheckList.new
      checklist.is_inclusion_list = true
      checklist.instructor = @account
    elsif (checklist = CheckList.find_by_id checklist_id).nil?
      flash[:error] = "Unknown checklist"
      redirect_to '/umlint/edit'
      return
    elsif checklist.instructor != @account
      flash[:error] = "Cannot modify checklist created by another instructor"
      redirect_to '/umlint/edit'
      return
    end

    isNew = checklist.id.nil?

    if checklist.updated_to(params)
      flash[:notice] = isNew ? "Checklist #{checklist.description} created" : "Checklist #{checklist.description} updated"
      redirect_to '/umlint'
    else
      flash[:error] = "Internal error; checklist could not be updated"
      redirect_to '/umlint/edit'
    end
  end

  def manage_password
    if need_login? # sets @account
      redirect_to '/umlint/login'
    else
      render :view => umlint_manage_password_path
    end
  end

end

software-development-lab/umltools/web/app/helpers/umlint_helper.rb
module UmlintHelper
end

software-development-lab/umltools/web/app/views/umlint/_navbar.erb
<div id="menu" class="collapse">
    <nav class="navbar navbar-default" role="navigation">
        <div class="container-fluid">

            <ul class="nav navbar-nav">
                <li class="<%= 'active' if current_page?(umlint_index_path) || current_page?(umlint_path) %>">
                    <%= link_to 'Home', umlint_index_path %>
                </li>
                <li class="<%= 'active' if current_page?(umlint_about_path) %>">
                    <%= link_to 'About', umlint_checks_path %>
                </li>
                <li class="<%= 'active' if current_page?(umlgrader_edit_path) %>">
                    <%= link_to 'Checklists', umlgrader_edit_path %>
                </li>
                <% if session[:account_id] && Account.find(session[:account_id].to_i).instructor? %>
                    <li class="<%= 'active' if current_page?(umlint_manage_password_path) %>">
                        <%= link_to 'Account', umlgrader_modify_instructor_path %>
                    </li>
                <% end %>
                <% if session[:account_id] %>
                    <li><%= link_to 'Logout', umlint_logout_path %></li>
                <% else %>
                    <li><%= link_to 'Login', umlint_login_path %></li>
                <% end %>
                <li><%= link_to 'UMLTools', '/' %></li>
                <li><%= link_to 'UMLGrader', umlgrader_index_path %></li>
                <li><%= link_to 'Bug Reporting', 'https://bitbucket.org/hasker/umltools/issues' %></li>
            </ul>
        </div>
    </nav>
</div>
<div class="pull-left">
    <button class="btn btn-primary" data-toggle="collapse" data-target="#menu">Menu <i class="fa fa-bars"></i></button>
</div>

software-development-lab/umltools/web/app/views/umlint/_results.html.erb
<div class=header>
    <div class=lint_header_title>
        UMLint Results
    </div>
</div>

<div class="lint-textarea col-lg-12">

    <div class="col-lg-10 col-md-9 col-md-9">

        <% if @check_list.nil? %>
            <h4>Issues for <%= @sub.orig_name %>:</h4>
        <% else %>
            <h4>Issues for <%= @sub.orig_name %>
                (using checks for <%= @check_list.description %>):</h4>
        <% end %>


        <p>
            <% if @suggestions.nil? %>
                <b>Error: invalid or corrupt model file. Please resubmit.</b>
            <% elsif @suggestions.empty? %>
                No issues found. But note this tool does not check for all possible
                errors; the author or team is responsible for examining the model
                closely for other errors.
            <% else %>
                <ol>
                    <% @suggestions.each_index do |six|
                      s = @suggestions[six]
                      show_more_info =
                              six == 0 ||
                                      @suggestions[six].explanation.name != @suggestions[six-1].explanation.name
                    %>
                        <li class=warning_item>
                            <%= s.message %>
                            <span id=warn<%= s.id %>>
         <% if show_more_info %>
           &nbsp;&nbsp;&nbsp;
           <%= link_to 'More information...',
                       "/umlint/show_suggestion_details/#{s.id}",
                       :remote => true
            %>
         <% end %>
         </span>
       <% end %>
       </ol>
     <% end %>


     <br/>

     <p>

     <div align=left class=ticket>
          Results ticket: <%= @sub.ticket %>
     </div>

     <%= form_tag('/umlint/index') do %>
       <div align=right>
            <div class=input_item><%= submit_tag 'Grade another solution',
                                      :class => 'btn btn-default' %></div>
       </div>
     <% end %>
   </div>

   </p>
</div>

software-development-lab/umltools/web/app/views/umlint/_show_examples.html.erb
<ul>
<li><em><span class=lint-explanation><%= @suggestion_item.explanation.examples %></span></em></li>
</ul>

software-development-lab/umltools/web/app/views/umlint/_view_checklist.html.erb
<% if @checklist_id != 0 && @check_list %>
    <table border=0>
        <tr>
            <td><label>Description:</label></td>
            <td colspan=3><%= @check_list.description %>
            </td>
        </tr>
        <tr>
            <td><label>Language:</label></td>
            <td style="width:12em"><%= @check_list.language %></td>
            <td><label>Organization:</label></td>
            <td><%= @check_list.organization %></td>
        </tr>
        <tr>
            <td><label>Retired:</label></td>
            <% if @check_list.retired %>
                <td><span class=attention>YES</span></td>
            <% else %>
                <td>no</td>
            <% end %>
            <td><label>Contact:</label></td>
            <td><%= @check_list.contact %></td>
        </tr>
    </table>

    <br>

    <p>
        A mark in the Apply column means the issue is always checked. If box is not checked, then any marked subissues
        are checked.
    </p>

    <div class="table-responsive">
        <table class="table table-striped table-hover table-bordered">
            <thead>
            <tr>
                <td class="center-text">Check</td>
                <td class="center-text">Apply?</td>
                <td class="center-text">Trigger</td>
                <td class="center-text">Rating</td>
            </tr>
            </thead>
            <tbody>
            <% @items.each { |item|
              checks = @included_checks[item.name.to_sym]
            %>
                <tr>
                    <td valign=top><%= item.name %></td>
                    <td valign=top align=center><%=
                        check_box_tag "include[#{item.id}]", true, checks && checks.include?(:ALL),
                                      :disabled => true %></td>
                    <td valign=top><%= item.description %></td>
                    <td align=center valign=top><%= item.precedence %></td>
                </tr>
                <tr>
                    <td></td>
                    <td></td>
                    <td valign=top colspan=2 class=lint-explanation>
                        <em>Subissues:</em>
                        <% detailed_items =
                                   Explanation.where(:name => item.name).take.detailed_issue_list
                        %>
                        <% if detailed_items.size == 1 %>
                            (<%= detailed_items[0] %>)
                        <% elsif detailed_items.size > 1
                             detailed_items.each { |subissue| %>
            <span style="white-space: nowrap;"><%=
                check_box_tag "checkitem[#{item.id}][#{subissue}]", true,
                              checks && checks.include?(subissue.to_sym),
                              :disabled => true
            %>&nbsp;<%= subissue %><%=
                ';' if subissue != detailed_items[-1]
            %></span>
                            <% } %>
                        <% end %>
                    </td>
                </tr>
            <% } %>
            </tbody>
        </table>
    </div>


<% end %>

software-development-lab/umltools/web/app/views/umlint/about.html.erb
<!--<TITLE>About UMLint</TITLE>-->

<div class=lint_header_title>
    About UMLint
</div>


<div class="lint-textarea">

    <div class="col-xs-12">
        <p>
            UMLint identifies common issues in use case and class diagrams generated by
            students using IBM Rhapsody or Rational Rose. The following people were
            involved:
        </p>
        <ul>
            <li>
                <a href="https://faculty-web.msoe.edu//hasker/">Dr. Rob Hasker</a>: initial
                concept, implementation of tool and website
            <li><a href="http://www.uwplatt.edu/~rowemi/">Dr. Mike Rowe</a>: concept,
                catalog of issues
            <li>Matt Booher (UW-Platteville student): prototype implementation
            <li>Rebecca Chandler, Matt Herman, CJ Kimpel, Brett Nockerts, and Andrew
                Scott (MSOE students): upgrades to implementation and website
        </ul>
        <p>
            The tool is written using the Ruby programming language and the Rails web
            development environment.
        </p>


        <p>
            To check diagrams generated by Enterprise Architect, select
            Model Import/Export from the Project menu and then select
            Export Package to XMI... In the Export Package to XMI screen,
            select Export Type "XMI 2.1", click on the ... beside Filename, 
            browse to the destination, set the type
            to "XMI Interchange (*.xmi)", set the filename, click Save to
            return to the Export dialog, and click on the Export button.
        </p>

        <p>
            To check diagrams generated in Rhapsody, visit the Tools menu and select
            "Export XMI from Rhapsody". Pick the UML 2.1 format and leave "Export
            Rhapsody Profiles" checked. If XMI is not enabled, you will need to contact
            your support staff.

        <p>
            For a full list of checks made by UMLint, see <a
        href="/umlint/checks">here</a> or click on the "All issues checked" button
            on the home page.
        </p>

        <p>
            There currently is no charge for using the tool. Ideas for additional
            checks are welcome. Instructors wishing to create checklists for use by
            their students should
            contact <a href="https://faculty-web.msoe.edu//hasker/">Dr. Hasker</a>. To
            log in to modify an existing checklist, click on the 'Edit checklist'
            button and the system will prompt for your information.
        </p>
    </div>

</div>

software-development-lab/umltools/web/app/views/umlint/checks.html.erb
<!--<TITLE>UMLint Checks</TITLE>-->

<div class=lint_header_title>
    UMLint Checks
</div>

<div class=lint-textarea>

    <div class="col-xs-12">
      <p>
          UMLint identifies common issues in use case and class diagrams generated by
          students using IBM Rhapsody or Rational Rose. The following people were
          involved:
      </p>
      <ul>
          <li>
              <a href="https://faculty-web.msoe.edu//hasker/">Dr. Rob Hasker</a>: initial
              concept, implementation of tool and website
          <li><a href="http://www.uwplatt.edu/~rowemi/">Dr. Mike Rowe</a>: concept,
              catalog of issues
          <li>Matt Booher (UW-Platteville student): prototype implementation
          <li>Rebecca Chandler, Matt Herman, CJ Kimpel, Brett Nockerts, and Andrew
              Scott (MSOE students): upgrades to implementation and website
      </ul>
      <p>
          The tool is written using the Ruby programming language and the Rails web
          development environment.
      </p>


      <p>
          To check diagrams generated by Enterprise Architect, select
          Model Import/Export from the Project menu and then select
          Export Package to XMI... In the Export Package to XMI screen,
          select Export Type "XMI 2.1", click on the ... beside Filename,
          browse to the destination, set the type
          to "XMI Interchange (*.xmi)", set the filename, click Save to
          return to the Export dialog, and click on the Export button.
      </p>

      <p>
          To check diagrams generated in Rhapsody, visit the Tools menu and select
          "Export XMI from Rhapsody". Pick the UML 2.1 format and leave "Export
          Rhapsody Profiles" checked. If XMI is not enabled, you will need to contact
          your support staff.
        </p>

      <p>
          There currently is no charge for using the tool. Ideas for additional
          checks are welcome. Instructors wishing to create checklists for use by
          their students should
          contact <a href="https://faculty-web.msoe.edu//hasker/">Dr. Hasker</a>. To
          log in to modify an existing checklist, click on the 'Checklist'
          button and the system will prompt for your information.
      </p>

      <p>
          Below is a list of the issues checked by UMLint.
      </p>
    </div>



    <p>

    <div class="table-responsive">
        <table class="table table-striped table-hover table-bordered">
            <thead>
            <tr>
                <td class="center-text">Check</td>
                <td class="center-text">Description</td>
                <td class="center-text">Rating</td>
                <td class="center-text">Diagram</td>
            </tr>
            </thead>
            <tbody>
            <% @explanations.each { |expl| %>
                <tr>
                    <td valign=top><%= expl.name %></td>
                    <td valign=top><%= expl.description %></td>
                    <td align=center valign=top><%= expl.precedence %></td>
                    <td valign=top><%= expl.diagram %></td>
                </tr>
                <tr>
                    <td valign=top align=right class=lint-explanation>
                        <em>description:</em></td>
                    <td colspan=3 valign=top class=lint-explanation>
                        <em><%= expl.explanation %></em>
                    </td>
                </tr>
            <% } %>
            </tbody>
        </table>
    </div>
</div>

software-development-lab/umltools/web/app/views/umlint/index.html.erb
<!--<TITLE>UMLint: Object-oriented model checker</TITLE>-->
<script>
    $(document).ready(function () {
        $(":file").filestyle();
    });
</script>

<div class=lint_header_title>
  UMLint: Object Oriented Model Checker
</div>

<div class="lint-textarea">

  <% if flash and flash[:notice] %>
      <div class="col-lg-6">
        <div class="alert alert-success fade in centered-text" role="alert">
          <button type="button" class="close" data-dismiss="alert">
            <span aria-hidden="true">×</span><span class="sr-only">Close</span></button>
          <%= flash[:notice] %>
        </div>
      </div>
  <% end %>

  <% if flash and flash[:error] %>
      <div class="col-lg-6">
        <div class="alert alert-danger fade in centered-text" role="alert">
          <button type="button" class="close" data-dismiss="alert">
            <span aria-hidden="true">×</span><span class="sr-only">Close</span></button>
          <%= flash[:error] %>
        </div>
      </div>
  <% end %>

  <div class="col-xs-12">

    <p>
      Browse to your model file, select a checklist, and click on 'Check'.

    </p>

    <!-- the multipart is what allows upload files: -->
    <%= form_tag('/umlint/results', :multipart => true) do %>

        <table>
            <tr>
                <td class=input_item>Model (.mdl, .xmi) file:&nbsp;&nbsp;</td>
                <td class=input_item>
                    <%= file_field :model_file, '', :size => 60, class: 'filestyle' %>
            </tr>
            <tr>
                <td class=input_item>Checklist to apply:&nbsp;</td>
                <td class=input_item><%=
                    select_tag 'checklist_id',
                               options_for_select(CheckList.check_types, @checklist_id.to_i), class: 'form-control'
                %>
            </tr>
            <tr>
                <td class=input_item>Type of file:&nbsp;</td>
                <td class=input_item><%=
                    select_tag 'file_type_id',
                               options_for_select([['UML Diagram', Problem::CLASS_DIAGRAM_TYPE],
                                                   ['Sequence Diagram', Problem::SEQUENCE_DIAGRAM_TYPE]]), class: 'form-control'
                %>
            </tr>
            <tr>
              <td class="input_item">Generate Diagram(If available)?&nbsp;</td>

              <td class="input_item">
                    <%= check_box_tag 'generate_diagram' %>
              </td>
            </tr>
            <tr>
            <td></td>
            <td class=input_item><%= submit_tag 'Check', class: 'btn btn-default' %></td>
          </tr>
        </table>


    <% end %>

    <br>
<!--
    <p>First time using UMLint? No problem! Click &lt;= link_to 'here', umlint_tutorial_path %&gt; for a tutorial.</p>
-->

  </div>
</div>

software-development-lab/umltools/web/app/views/umlint/results.html.erb
<%= render :partial => 'results' %>

software-development-lab/umltools/web/app/views/umlint/tutorial.erb
<!DOCTYPE html>
<html>
<head></head>
<body>
<div class=lint_header_title>
  UMLint: Object Oriented Model Checker
</div>

<div class="lint-textarea">
  <div class="col-xs-12">
    <h1>Tutorial</h1>
    <ol>
      <li><h3>Create a class or sequence diagram in a program capable of exporting to XMI format such as Enterprise Architect.</h3></li>
      <ul>
        <li>You may be tempted to structure your project like the pictures below.</li>
        <li>Do NOT do this!</li>
        <%= image_tag("Tutorial-Screenshot-7.png", :alt => "Do NOT do this!") %>
        <%= image_tag("Tutorial-Screenshot-6.png", :alt => "Do NOT do this!") %>
        <li>Instead use a workflow like the one in the picture below.</li>
        <li>If you don't, the generated XMI will contain elements of both the class and sequence diagram.</li>
        <%= image_tag("Tutorial-Screenshot-9.png", :alt => "Do (do) this!") %>
      </ul>
      <li><h3>Export the created package to generate an XMI file.</h3></li>
      <ul>
        <li>Use the menu to select the package you want to export.</li>
        <%= image_tag("Tutorial-Screenshot-0.png", :alt => "File menu (the right way). :D") %>
        <li>Choose the desired path, and then click the 'export' button.</li>
        <%= image_tag("Tutorial-Screenshot-1.png", :alt => "Export XMI.") %>
      </ul>
      <li><h3>Submit the assignment via UMLGrader.</h3></li>
      <ul>
        <li>Choose and upload the assignment you want to check.</li>
        <li>Choose the checklist that you want to implement.</li>
        <li>Don't forget to specif the type of file you are uploading!</li>
        <%= image_tag("Tutorial-Screenshot-12.png", :alt => "Submit an assignment.") %>
      </ul>
      <li><h3>View submission results.</h3></li>
      <ul>
        <%= image_tag("Tutorial-Screenshot-13.png", :alt => "View results.") %>
      </ul>
    </ol>
    <h1>Sample Files</h1>
    <ul>
      <h3>The sample file package includes the following files.</h3>
      <ul>
        <li>Class Diagram [EAP]</li>
        <li>Sequence Diagram [EAP]</li>
        <li>Class Diagram (Problem) [XMI]</li>
        <li>Class Diagram (Solution) [XMI]</li>
        <li>Sequence Diagram (Problem) [XMI]</li>
        <li>Sequence Diagram (Solution) [XMI]</li>
      </ul>
      <h3><%= link_to 'Sample File Pack Download', umlgrader_tutorial_download_path %></h3>
    </ul><br>
    <%= link_to 'Back To UMLint', umlint_path %>
  </div>
</div>
</body>
</html>